import { AppProvider } from './provide'

import type { Metadata } from 'next'
import '@workspace/ui/globals.css'

import './globals.css'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className="antialiased"
      >
        <AppProvider>
          {children}
        </AppProvider>
      </body>
    </html>
  )
}
